#!/usr/bin/env sh
set -eu
exec 2>&1

COMMAND=/usr/local/bin/php
OPTS="bin/console messenger:consume transaction --time-limit=3600 -vvv"

# Check command is executable or not
test -x ${COMMAND} || exit 0
cd /app
while true;do
	date +%f
	exec chpst -uwww-data ${COMMAND} ${OPTS}
done
