version: '3.7'
services:
  db:
    container_name: cmhub_mysql
    image: mysql:5.7
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
    networks:
      - esnet

  php:
    container_name: cmhub_php
    build: ./docker/php
    ports: ['9000:9001']
    links:
      - db
    volumes:
      - .:/var/www/cmhub:cached
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      COMPOSER_MEMORY_LIMIT: -1
#      XDEBUG_CONFIG: remote_host=10.31.9.77
#      PHP_IDE_CONFIG: serverName=localhost
    networks:
      - esnet

  nginx:
    container_name: cmhub_nginx
    build: ./docker/nginx
    ports: ['80:80']
    links:
      - php
    volumes:
      - ./docker/nginx/logs:/var/log/nginx:cached
      - ./docker/xdebug/logs/:/tmp/xdebug_log/
      - .:/var/www/cmhub:cached
    networks:
      - esnet
        
  worker:
    build: ./docker/worker
    container_name: cmhub_worker
    volumes:
      - .:/var/www/cmhub
    environment:
      COMPOSER_MEMORY_LIMIT: -1
    networks:
      - esnet

networks:
  esnet: