fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     App\Application\Sonata\UserBundle\Entity\User
    group:
        group_class:   App\Application\Sonata\UserBundle\Entity\Group

    service:
        user_manager: sonata.user.orm.user_manager
        mailer: fos_user.mailer.noop

    from_email:
        address: "user@mail.com"
        sender_name: "user"
