security:
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
        App\Entity\CmUser:
            algorithm: bcrypt

    providers:
        cmuser_provider:
            entity:
                class: App:CmUser
                property: username

        iresa_provider:
            memory:
                users:
                    iresa:
                        # cAq9xLKLNu7xqwqqz9stMNgAkZMSqVG7ya6FFrBn
                        password: '%internal.api.iresa.password%'

        memory_provider:
            memory:
                users:
                    eai:
                        # password: 17s8msLXKkMVy0mP0BlT0BN7bRsMNEEE
                        password: '%internal.api.eai.password%'
                    r2d2:
                        # password: NA8maUd9RQnx9FHbaTREpJe3wu8FCTsp
                        password: '%internal.api.r2d2.password%'
                    booking:
                        # password: nGVdcBcNs8C3pUG6eX82mUnxvkpVveU9
                        password: '%internal.api.booking.password%'
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        wubook:
            pattern: ^/api/wubook
            anonymous: ~
            logout: ~
            stateless: true
            provider: cmuser_provider
            guard:
                authenticators:
                    - App\Security\WubookAuthenticator

        availpro:
            pattern: ^/api/ext/xml/availpro
            anonymous: ~
            logout: ~
            stateless: true
            provider: cmuser_provider
            guard:
                authenticators:
                    - App\Security\AvailproAuthenticator

        smarthotel:
            pattern: ^/api/ext/soap/ota/smarthotel
            methods: [POST]
            anonymous: ~
            logout: ~
            stateless: true
            provider: cmuser_provider
            guard:
                authenticators:
                    - App\Security\SmartHotelAuthenticator

        travelclick:
            pattern: ^/api/ext/soap/ota/travelclick
            methods: [POST]
            anonymous: ~
            logout: ~
            stateless: true
            provider: cmuser_provider
            guard:
                authenticators:
                    - App\Security\TravelClickAuthenticator

        siteminder:
            pattern: ^/api/ext/soap/ota/siteminder
            methods: [POST]
            anonymous: ~
            logout: ~
            stateless: true
            provider: cmuser_provider
            guard:
                authenticators:
                    - App\Security\SoapAuthenticator

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        iresa:
            http_basic: ~
            pattern: ^/api/int/rest/v1/PushBookings
            provider: iresa_provider

        bb8:
            pattern: ^/api/external
            anonymous: ~
            logout: ~
            stateless: true
            provider: cmuser_provider
            guard:
                authenticators:
                    - App\Security\BB8Authenticator
        int:
            http_basic: ~
            pattern: ^/api/int/
            provider: memory_provider
        r2d2:
            http_basic: ~
            pattern: ^/r2d2/
            provider: memory_provider
        booking:
            http_basic: ~
            pattern: ^/templates/
            provider: memory_provider
        soap_v1:
            pattern: ^/api/ext/soap/ota/v1
            methods: [POST]
            anonymous: ~
            logout: ~
            stateless: true
            provider: cmuser_provider
            guard:
                authenticators:
                    - App\Security\SoapAuthenticator

        soap_v2:
            pattern: ^/api/ext/soap/ota/v2/
            methods: [POST]
            anonymous: ~
            logout: ~
            stateless: true
            provider: cmuser_provider
            guard:
                authenticators:
                    - App\Security\SoapAuthenticator

        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
                default_target_path:   /admin/dashboard
            logout:
                path:           /admin/logout
                target:         /admin/login
            anonymous:          true
        main:
            pattern:             .*
            context:             user
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:             true
            anonymous:          true

    access_control:
        # Admin login page needs to be accessed without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(SECURE_SCHEME)%' }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(SECURE_SCHEME)%' }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(SECURE_SCHEME)%' }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(SECURE_SCHEME)%' }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin/, role: [ROLE_USER], requires_channel: '%env(SECURE_SCHEME)%' }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
