monolog:
    handlers:
        main:
            buffer_size: 10
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
        nested:
            buffer_size: 10
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            buffer_size: 10
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
#        deprecation:
#            type: stream
#            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
#        deprecation_filter:
#            type: filter
#            handler: deprecation
#            max_level: info
#            channels: ["php"]
        kibana:
            buffer_size: 10
            type: stream
            path: "%kernel.logs_dir%/cmhub.log"
            formatter: monolog.formatter.logstash
            channels: ['cmhub']
