#####  EAI calls   #####
api_eai_smoke_test:
    path: /api/int/rest/v1/auth_check
    defaults: { _controller: App\Controller\EaiController::smokeTestAction }
    methods:  [POST]

api_eai_partner:
    path: /api/int/rest/v1/UpdatePartner
    defaults: { _controller: App\Controller\EaiController::partnerAction }
    methods:  [POST]

api_eai_product:
    path: /api/int/rest/v1/UpdateProduct
    defaults: { _controller: App\Controller\ProductController::productAction }
    methods:  [POST]

api_eai_callback:
    path: /api/int/rest/v1/UpdateStatus
    defaults: { _controller: App\Controller\TransactionController::updateStatusAction }
    methods:  [POST]
